import 'package:ishci_app/config/imports.dart';

class HomeController extends GetxController {
  List carti = [
    {
      "profile_img": NetworkImages.bola,
      "name": "Karimov Salim",
      "time_botton": "9:00|17:00",
      "region": "Toshkent",
      "time": "7:32",
      "eye": "1137",
      "summa": "1 732 000",
    },
    {
      "profile_img": NetworkImages.bola,
      "name": "Yuzupov Sobir",
      "time_botton": "9:00|19:00",
      "region": "Andijon",
      "time": "9:32",
      "eye": "137",
      "summa": "1 239 000",
    },
    {
      "profile_img": NetworkImages.bola,
      "name": "Chapayev Bactjon",
      "time_botton": "9:00|19:00",
      "region": "Toshkent",
      "time": "10:32",
      "eye": "1327",
      "summa": "2 239 000",
    },
    {
      "profile_img": NetworkImages.bola,
      "name": "Qodirov Komil",
      "time_botton": "9:00|19:00",
      "region": "Samarqant",
      "time": "14:32",
      "eye": "1137",
      "summa": "1 939 000",
    },
    {
      "profile_img": NetworkImages.bola,
      "name": "Tursunboyev Yahyo",
      "time_botton": "9:00|19:00",
      "region": "Buxoro",
      "time": "9:32",
      "eye": "107",
      "summa": "3 239 000",
    },
    {
      "profile_img": NetworkImages.bola,
      "name": "Nigmatov Asat",
      "time_botton": "9:00|19:00",
      "region": "Jizzax",
      "time": "19:32",
      "eye": "1017",
      "summa": "2 239 000",
    },
    {
      "profile_img": NetworkImages.bola,
      "name": "Qo'chqorov Eldor",
      "time_botton": "9:00|19:00",
      "region": "Samarqant",
      "time": "13:32",
      "eye": "237",
      "summa": "1 200 000",
    },
    {
      "profile_img": NetworkImages.bola,
      "name": "Qobulov Dilshod",
      "time_botton": "9:00|19:00",
      "region": "Andijon",
      "time": "9:32",
      "eye": "637",
      "summa": "5 239 000",
    },
  ];
}
